swagger: '2.0'

# basic meta information
info:
  title: Sievinator API
  version: '1.0'
  description: The Sievinator for all your prime number needs!

# technical configuration
basePath: /
produces:
- application/json
consumes:
- application/json

paths:
  # Primes
  '/primes/nth/{n}':
    get:
      summary: get the nth prime
      description: |
       get the nth prime
      tags:
      - Primes
      operationId: 'sieve.api/primes-nth'
      parameters:
      - $ref: '#/parameters/Number'
      responses:
        200:
          description: The nth prime
          schema:
            type: integer
  '/primes/upto/{n}':
    get:
      summary: primes up to number
      description: |
        all the primes up to and including this number (if it is prime)
      tags:
      - Primes
      operationId: 'sieve.api/primes-up-to'
      parameters:
      - $ref: '#/parameters/Number'
      responses:
        200:
          description: The primes
          schema:
            type: array
            items:
              type: number
              format: integer
  '/primes/from/{from}/to/{to}':
    get:
      summary: primes up to number
      description: |
        all the primes up to and including this number (if it is prime)
      tags:
      - Primes
      operationId: 'sieve.api/primes-from-to'
      parameters:
        - name: from
          in: path
          description: The inclusive starting point
          required: true
          type: number
          format: integer
        - name: to
          in: path
          description: The inclusive endpoint
          required: true
          type: number
          format: integer
      responses:
        200:
          description: The primes between from and to
          schema:
            type: array
            items:
              type: number
              format: integer
  # The Sieve itself
  '/sieve/state':
    get:
      summary: The current state of the sieve
      description: |
        The internal state of the sieve
      tags:
      - Sieve
      operationId: 'sieve.api/sieve-state'
      responses:
        200:
          description: The primes
  '/sieve/block-size':
    get:
      summary: The current block size when growing the sieve
      description: |
        The Sievinator grows primes blocks at a time; this is the current block size
      tags:
      - Sieve
      operationId: 'sieve.api/sieve-block-size'
      responses:
        200:
          description: The primes
          schema:
            type: array
            items:
              type: number
              format: integer
    post:
      summary: Set the current block size
      description: |
        The Sievinator grows primes blocks at a time; change the block size
      tags:
      - Sieve
      operationId: 'sieve.api/sieve-block-size'
      parameters:
      - name: size
        in: formData
        description: The new block size
        required: true
        type: number
        format: integer
      responses:
        200:
          description: The old block size
          schema:
            type: integer
            format: integer

# definitions

parameters:
  Number:
    name: n
    in: path
    type: number
    format: integer
    description: The number in question
    required: true
    #pattern: "^[a-z][a-z0-9-]*[a-z0-9]$"


