swagger: '2.0'

# basic meta information
info:
  title: Sievinator API
  version: '1.0'
  description: The Sievinator for all your prime number needs!

# technical configuration
basePath: /
produces:
- application/json
consumes:
- application/json

paths:
  # Primes
  '/primes/nth/{n}':
    get:
      summary: get the nth prime
      description: |
       get the nth prime
      tags:
      - Primes
      operationId: 'sieve.api/primes-nth'
      parameters:
      - $ref: '#/parameters/Number'
      responses:
        200:
          description: The nth prime
          schema:
            type: integer

# definitions

parameters:
  Number:
    name: n
    in: path
    type: number
    format: integer
    description: The number in question
    required: true
    #pattern: "^[a-z][a-z0-9-]*[a-z0-9]$"


